In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cardio_train.csv', sep = ';')
df.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0   0  18393       2     168    62.0    110     80            1     1      0   
1   1  20228       1     156    85.0    140     90            3     1      0   
2   2  18857       1     165    64.0    130     70            3     1      0   
3   3  17623       2     169    82.0    150    100            1     1      0   
4   4  17474       1     156    56.0    100     60            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       0       1  
3     0       1       1  
4     0       0       0

In [3]:
df['years'] = (df['age'] / 365).round(0)
df['years'] = pd.to_numeric(df['years'], downcast = 'integer')
df['Cardio'] = df['cardio']

In [4]:
df = df.drop('age', axis = 1)

In [5]:
#df = df.drop('id', axis = 1)
df = df.drop('cardio', axis = 1)

In [6]:
X = np.array(df.iloc[:, :-1].values, dtype = np.float128)
Y = df.iloc[:, -1].values

In [7]:
df.head()

id  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0   0       2     168    62.0    110     80            1     1      0     0   
1   1       1     156    85.0    140     90            3     1      0     0   
2   2       1     165    64.0    130     70            3     1      0     0   
3   3       2     169    82.0    150    100            1     1      0     0   
4   4       1     156    56.0    100     60            1     1      0     0   

   active  years  Cardio  
0       1     50       0  
1       1     55       1  
2       0     52       1  
3       1     48       1  
4       0     48       0

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 1)

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
model = LogisticRegression()

In [11]:
model.fit(X_train, Y_train)

/home/sujay/.local/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, model.predict(X_test))

TN = cm[0][0]
TP = cm[1][1]
FN = cm[1][0]
FP = cm[0][1]

print(cm)
print((TP+TN)/(TP+TN+FP+FN))

[[6464 2145]
 [3120 5771]]
0.6991428571428572


In [13]:
model.predict(X_test)

array([1, 1, 1, ..., 1, 1, 0])

In [14]:
Y_test

array([1, 1, 1, ..., 1, 1, 0])

98.31

In [16]:
lst = [2.       , 170.       ,  80.       , 130.       ,  90.       ,
         1.       ,   1.       ,   0.       ,   0.       ,   1.       ,
        27.6816609,  58.       ]

In [17]:
lst

[2.0, 170.0, 80.0, 130.0, 90.0, 1.0, 1.0, 0.0, 0.0, 1.0, 27.6816609, 58.0]

In [18]:
type(lst)

list

In [23]:
arr = np.array([lst])

In [24]:
arr

array([[  2.       , 170.       ,  80.       , 130.       ,  90.       ,
          1.       ,   1.       ,   0.       ,   0.       ,   1.       ,
         27.6816609,  58.       ]])

In [25]:
model.predict(arr)[0]

1

In [26]:
p =(model.predict_proba(arr))
round(p[0][1] * 100, 2)

98.31